### ISSUE TITLE
accessing a random replica, after the stack is deployed, cause MongoError: not master and slaveOk=false 

### ISSUE THREAD

**Issue by dottgonzo** [smartsdk/mongo-rs-controller-swarm#7]
Hi,
thanks for your solution to provide a simple stack to deploy a mongodb cluster in a swarm mode environment. 

i'm trying your compose, so i've deployed an instance of mongo-express to be able to test it. Mongo-express can connect to the service, but accessing a random replica can cause errors like this one:

 ```
{"name":"MongoError","message":"not master and slaveOk=false","ok":0,"errmsg":"not master and slaveOk=false","code":13435}

 ```

and i don't know if i can write the db accessing it from a replica.

My goal is to be able to use the instances without a persistent volume, by having ever some replica alive, from which the others can be restored in case of restarting/fail/scale (and in the meanwhile i do a continous backup).

A possible solution is to have a service that act ever as a master, and the other services that acts ever as replica, on the same stack, but in this case all the traffic is directed ever to the master so the others works only as backup services. Maybe a proxy in conjunction to your controller is needed or i'm forget something.

This is my stack file:

 ```
version: '3.2'

services:

  mongo:
    image: mongo:${MONGO_VERSION:-3.2}
    entrypoint: [ "/usr/bin/mongod", "--replSet", "${REPLICASET_NAME:-rs}", "--journal", "--smallfiles"]
    ports:
      - "${MONGO_PORT:-27017}:27017"
    # The usage of volume provides persistence, but may work correctly only with 1 volume per node (that's why global mode is recommended)
    networks:
      - mongo
    secrets:
    # to avoid changes to the original mongo image, we import the healthcheck script using secrets
      - mongo-healthcheck
    # it simply checks that the client can connect to mongo. No test is run w.r.t. the cluster.
    healthcheck:
        test: ["CMD", "bash", "/run/secrets/mongo-healthcheck"]
        interval: 1m
        timeout: 10s
        retries: 3
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 1m30s

  controller:
    image: martel/mongo-replica-ctrl:latest
    volumes:
      # TODO: Avoid exposing the docker socket (security issue)
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERLAY_NETWORK_NAME=${OVERLAY_NETWORK_NAME:-mongo}
      - MONGO_SERVICE_NAME=${STACK_NAME:-mongo}_mongo
      - REPLICASET_NAME=${REPLICASET_NAME:-rs}
      - MONGO_PORT=27017
      # - DEBUG=1 #uncomment to debug the script
    entrypoint: python /src/replica_ctrl.py
    networks:
        - mongo
    depends_on:
        - "mongo"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure

secrets:
  # to avoid changes to the original mongo image, we import the healthcheck script using secrets
  mongo-healthcheck:
    file: mongocluster/mongo-healthcheck

networks:
  mongo:
    external: true
 ```

Docker version 17.06.1-ce, build 874a737
